export const BINGO_TILE_DRAW_COUNT = 20;

type BingoTakeLocale = 'en' | 'fr';

const BINGO_TAKE_BANKS: Record<BingoTakeLocale, readonly string[]> = {
	fr: [
		'Drama pour une virgule',
		'Dossier de 2019 ressorti',
		'Avis tiède, ton nucléaire',
		'Opinion en mode prophétie',
		'Le chaos en roue libre',
		'Punchline morte au sol',
		'Respect réclamé trop tard',
		'Expert LinkedIn instantané',
		'Départ de X annoncé sur X',
		'Silence de screen record',
		'Jugement sans procès',
		'Complot devenu business',
		'Alpha en PLS légère',
		'Ex transformé en étude',
		'Ton commission d’enquête',
		'Excuse avec insulte incluse',
		'Micro ouvert, dignité fermée',
		'Dignité enterrée en live',
		'Morale après mauvaise foi',
		'Ratio senti avant le tweet',
		'Source: trust me bro',
		'Victime professionnelle',
		'Take volée puis mal digérée',
		'Menace juridique en carton',
		'Brainstorm de mauvaise foi',
		'Conseil non demandé',
		'Nuance assassinée en direct',
		'Trauma dump stratégique',
		'Burn-out de bon sens',
		'Certitude sans carburant',
		'Clash en mousse premium',
		'Victim card en économie',
		'Thread cité comme Bible',
		'Gros ego, petit micro',
		'Confession trop gratuite',
		'Le niveau descend au sous-sol',
		'Masterclass de gêne',
		'Vanne recyclée trois fois',
		'Calme toxique activé',
		'Fausse modestie détectée',
		'Preuve remplacée par le volume',
		'Analyse sortie du congélo',
		'Débat devenu garderie',
		'Flex de facture impayée',
		'Timing social catastrophique',
		'Argument en carton humide',
		'Le réel quitte la pièce',
		'Monologue sans permis',
		'Opinion périmée servie chaude',
		'Cringe en haute définition',
		'Résumé faux mais confiant',
		'Pardon sans remise en question',
		'Égo fragile sous vitrine',
		'Hot take à température ambiante',
		'Storytime de trop',
		'Menace de mute dramatique',
		'Grand moment de petit pouvoir',
		'Problème perso en public',
		'Philo de comptoir premium',
		'Source perdue en 4G',
		'Tweet fantôme inventé',
		'Clash sponsorisé par l’ennui',
		'Vérité générale très personnelle',
		'Comparaison totalement illégale',
		'Confidence qui aurait dû rester offline',
		'Bad buzz en préparation',
		'Air supérieur, fond vide',
		'Victime du bouton unmute',
		'Émotion prise en otage',
		'Gros mot pour petit argument',
		'Déni servi avec aplomb',
		'Story arc humiliant',
		'Le second degré démissionne',
		'Contradiction en moins de 30s',
		'Malaise avec supplément sauce',
		'Clash perdu à domicile',
		'Réponse longue, idée courte',
		'Fake calme, vraie rancune',
		'Désaccord devenu thérapie',
		'Opinion copiée sans citer',
		'Nuance expulsée du Space',
		'Rapport de force imaginaire',
		'Vécu brandi comme passe-droit',
		'Punchline sous assistance',
		'Lecture du réel en 144p',
		'Certitude de fin de soirée',
		'Réflexion bloquée en brouillon',
		'Grand oral de mauvaise foi',
		'Personal branding en détresse',
		'Analyse au doigt mouillé',
		'Fierté mal placée',
		'Évidence refusée par principe',
		'Dérapage présenté comme nuance',
		'Aplomb inversement proportionnel',
		'Mini scandale, maxi posture',
		'Monologue en otage collectif',
		'Vérité sortie du chapeau',
		'Balle perdue très ciblée',
		'Énervement sans plan',
		'Conclusion avant réflexion'
	],
	en: [
		'Drama over one comma',
		'2019 receipts revived',
		'Mild take, nuclear tone',
		'Opinion as prophecy',
		'Chaos fully unlocked',
		'Punchline dead on arrival',
		'Respect demanded too late',
		'Instant LinkedIn expert',
		'Leaving X announced on X',
		'Screen-record silence',
		'Judgment without trial',
		'Conspiracy turned business',
		'Fake alpha lightly panics',
		'Ex turned case study',
		'Testimony voice activated',
		'Apology with insult included',
		'Open mic, closed dignity',
		'Dignity buried live',
		'Morals after bad faith',
		'Ratio felt before posting',
		'Source: trust me bro',
		'Professional victim mode',
		'Stolen take, poorly digested',
		'Cardboard legal threat',
		'Bad-faith brainstorm',
		'Unsolicited advice',
		'Nuance murdered live',
		'Strategic trauma dump',
		'Common sense burnout',
		'Confidence without fuel',
		'Premium foam beef',
		'Budget victim card',
		'Thread quoted as scripture',
		'Big ego, tiny mic',
		'Confession nobody ordered',
		'The level hits basement',
		'Masterclass in awkward',
		'Joke recycled three times',
		'Toxic calm activated',
		'Fake humility detected',
		'Proof replaced by volume',
		'Frozen analysis reheated',
		'Debate turned daycare',
		'Unpaid-invoice flex',
		'Social timing disaster',
		'Soggy-cardboard argument',
		'Reality leaves the room',
		'Monologue without a license',
		'Expired opinion served hot',
		'Cringe in HD',
		'Wrong summary, full confidence',
		'Apology, zero reflection',
		'Fragile ego on display',
		'Room-temperature hot take',
		'One storytime too many',
		'Dramatic mute threat',
		'Small power trip moment',
		'Personal issue, public stage',
		'Premium barstool philosophy',
		'Source lost on 4G',
		'Imaginary ghost tweet',
		'Boredom-sponsored beef',
		'Very personal universal truth',
		'Completely illegal comparison',
		'Offline thought said out loud',
		'Bad buzz in progress',
		'Superior tone, empty core',
		'Victim of the unmute button',
		'Emotion held hostage',
		'Big word, tiny argument',
		'Denial served confidently',
		'Humiliating story arc',
		'Irony resigns from the room',
		'Contradiction under 30s',
		'Awkward with extra sauce',
		'Home-field beef loss',
		'Long answer, short idea',
		'Fake calm, real grudge',
		'Disagreement turned therapy',
		'Copied opinion, no credit',
		'Nuance ejected from Space',
		'Imaginary power struggle',
		'Life story as free pass',
		'Punchline on life support',
		'Reality read in 144p',
		'Late-night certainty',
		'Thought stuck in draft',
		'Bad-faith final exam',
		'Personal brand in distress',
		'Vibes-based analysis',
		'Misplaced pride',
		'Obvious point refused',
		'Spiral sold as nuance',
		'Confidence inversely related',
		'Mini scandal, maxi posture',
		'Collective hostage monologue',
		'Truth pulled from a hat',
		'Very targeted stray shot',
		'Anger with no plan',
		'Conclusion before thought'
	]
};

export function getRandomBingoTileTexts(locale: string, count = BINGO_TILE_DRAW_COUNT) {
	const bank = BINGO_TAKE_BANKS[normalizeBingoTakeLocale(locale)];
	const shuffled = [...bank];

	for (let index = shuffled.length - 1; index > 0; index -= 1) {
		const target = Math.floor(Math.random() * (index + 1));
		[shuffled[index], shuffled[target]] = [shuffled[target], shuffled[index]];
	}

	return shuffled.slice(0, count);
}

function normalizeBingoTakeLocale(locale: string): BingoTakeLocale {
	return locale === 'fr' ? 'fr' : 'en';
}
